CREATE SEQUENCE USER_ID;

CREATE TABLE USER (
  ID INTEGER DEFAULT user_id.NEXTVAL PRIMARY KEY,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  LOGIN VARCHAR(255)
);

CREATE TABLE TOKEN (
  TOKEN VARCHAR(384) PRIMARY KEY,
  EXPIRATION_DATE TIMESTAMP NOT NULL ,
  CREATION_DATE TIMESTAMP NOT NULL,
  IS_REVOKED INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)